FROM eclipse-temurin:17-jdk-jammy
RUN mkdir /app
RUN mkdir /app/data
COPY target/article-management-1.0.0-SNAPSHOT.jar /app/app.jar
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh
WORKDIR /app
