FROM eclipse-temurin:17-jdk-jammy
# COPY ./target/user-service-1.0.0-SNAPSHOT.jar /app/app.jar
# ENTRYPOINT java -jar /app/app.jar

# RUN mkdir /app
# COPY ./target/user-service-1.0.0-SNAPSHOT.jar /app/app.jar
# WORKDIR /app
# CMD "java" "-jar" "app.jar"
# ENTRYPOINT ["java","-jar","/app.jar"]


# ARG JAR_FILE=target/user-service-1.0.0-SNAPSHOT.jar
# ADD ${JAR_FILE} app.jar
# ENTRYPOINT ["java","-jar","/app.jar"]